include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    # riverpod_lint is discovered and run through custom_lint.
    - custom_lint
  errors:
    unused_import: warning

linter:
  rules:
    prefer_single_quotes: true
